FROM maven:3-alpine
ARG DOCKER_URL=https://download.docker.com/linux/static/stable/x86_64
ARG DOCKER_VERSION=18.03.1-ce
RUN curl -fsSL ${DOCKER_URL}/docker-${DOCKER_VERSION}.tgz | tar zxvf - --strip 1 -C /usr/bin docker/docker
