apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-svc-nginx-config-map
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  2;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;

        upstream authorization-service {
            server 127.0.0.1:8000;
        }

        server {
            listen 80;

            location / {
                proxy_pass         http://authorization-service;
                proxy_redirect     off;
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc-service
spec:
  type: LoadBalancer
  selector:
    app: authorization-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc-deployment
spec:
  selector:
    matchLabels:
      app: authorization-service
  replicas: 1
  template:
    metadata:
      labels:
        app: authorization-service
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: auth-svc-nginx-config-map
      containers:
        - name: authorization-service
          image: authorization-service:latest
          imagePullPolicy: Never
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
